SRC =	../git_get_next_line/get_next_line.c
		../git_get_next_line/get_next_line_utils.c

echo:

all:
		cc get_next_line_main.c $(SRC) -D BUFFERSIZE=42

clean:
		rm a.out

re: clean all

.phony: re clean all 